# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project <sqaaas@ibergrid.eu>
# SPDX-FileContributor: Pablo Orviz <orviz@ifca.unican.es>
#
# SPDX-License-Identifier: GPL-3.0-only

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.12.0
  hooks:
    - id: black
      files: step.py
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
    - id: isort
      files: step.py
- repo: https://github.com/pycqa/flake8
  rev: 3.7.9
  hooks:
    - id: flake8
      files: step.py
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
    - id: docformatter
      args: [--in-place, --config, ./setup.cfg]
      files: step.py
- repo: https://github.com/fsfe/reuse-tool
  rev: v1.0.0
  hooks:
    - id: reuse
