# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project.
# SPDX-FileContributor: 2017-2024 Pablo Orviz <orviz@ifca.unican.es>
#
# SPDX-License-Identifier: GPL-3.0-only

name: 'Step definition within a SQAaaS quality assessment'
description: 'Define a step (tool+args) in the evaluation of a given criterion within the SQAaaS quality assessment'
author: 'Pablo Orviz <orviz@ifca.unican.es>'
inputs:
  name:
    description: Name of the step
    required: true
  tool:
    description: Tool to execute within the step
    required: true
  container:
    description: Docker container image where the step shall be executed
    required: false
    default: ''
  # For shell commands
  commands:
    description: List of shell commands to execute
    required: false
    default: ''
  # For 'pytest' tool
  test_path:
    description: Path to test cases
    required: false
    default: ''
  # For 'tox' tool
  tox_env:
    description: tox environment
    required: false
    default: ''
outputs:
  step:
    description: 'Definition of the step in JSON format (in accordance with SQAaaS API specification)'
runs:
  using: 'docker'
  image: 'Dockerfile'
