[project]
name = "sqaaas-step-action"
version = "1.1.0"
authors = [
  { name="Pablo Orviz Fernández", email="orviz@ifca.unican.es" }
]
description = "Step definition within a SQAaaS assessment"
readme = "README.md"

[tool.isort]
profile = "black"
